const http = require('http');
const fs = require('fs');
const path = require('path');
const { exec, spawn, execSync } = require('child_process');
const { Client } = require('ssh2');
const os = require('os');
const events = require('events');

const PORT = 3456;
const GLOBAL_DIR = path.join(os.homedir(), '.gemini-bridge');
const CONFIGS_DIR = path.join(GLOBAL_DIR, 'configs');
const SETTINGS_FILE = path.join(GLOBAL_DIR, 'settings.json');

if (!fs.existsSync(CONFIGS_DIR)) fs.mkdirSync(CONFIGS_DIR, { recursive: true });

let globalSettings = { 
    intercept_terminal: false,
    instruction_filename: 'GEMINI.md'
};

if (fs.existsSync(SETTINGS_FILE)) {
    try { 
        const saved = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8')); 
        globalSettings = { ...globalSettings, ...saved };
    } catch(e) {
        console.error("Error loading settings:", e);
    }
}

const logEmitter = new events.EventEmitter();

function ensureSshKey() {
    const sshDir = path.join(os.homedir(), '.ssh');
    const keyPath = path.join(sshDir, 'id_rsa_bridge');
    if (!fs.existsSync(sshDir)) fs.mkdirSync(sshDir, { recursive: true, mode: 0o700 });
    if (!fs.existsSync(keyPath)) {
        execSync(`ssh-keygen -t rsa -b 2048 -f "${keyPath}" -N ""`, { stdio: 'ignore' });
    }
    return fs.readFileSync(`${keyPath}.pub`, 'utf8');
}

function generateActivationFiles(sessionName, config, originalName, hasMutagen) {
    const activateContent = `
# Autogenerated by Agent Tunnel
export GEMINI_BRIDGE_SESSION="${sessionName}"
export GEMINI_BRIDGE_HOST="${config.host}"
export GEMINI_BRIDGE_USER="${config.user}"
export GEMINI_BRIDGE_HAS_MUTAGEN="${hasMutagen}"
export GEMINI_BRIDGE_PROJECT_ROOT="${process.cwd()}"

if [ "\${GEMINI_BRIDGE_INTERCEPT:-${globalSettings.intercept_terminal}}" = "true" ]; then
    source "${path.join(process.cwd(), 'gemini-bridge/scripts/shell-hook.sh')}"
fi

echo -e "\\x1b[36m[Agent Tunnel]\\x1b[0m Environment activated: ${originalName}"
`.trim();
    fs.writeFileSync(path.join(process.cwd(), 'activate.sh'), activateContent);
    
    const instrFile = globalSettings.instruction_filename || 'GEMINI.md';
    const mdContent = `
# Agent Tunnel: ${originalName}

This project is configured to work on a remote environment via SSH transparently.

## Active Configuration
- **Host:** ${config.host}
- **User:** ${config.user}
- **Remote Path:** ${config.remote_path}
- **Sync Status:** ${hasMutagen ? 'ACTIVE' : 'DISABLED (Direct Command Mode)'}

## Interception Rules
**YOU ARE FORBIDDEN** from using direct commands like \`ls\`, \`npm start\`, etc., if they should run on the remote machine.
Instead, **ALWAYS** prefix your terminal commands with the tunnel script:

\`\`\`bash
./gemini-bridge/scripts/remote-exec.sh "your command here"
\`\`\`

This will automatically send the command to the remote device and show logs in the web interface.
`.trim();
    fs.writeFileSync(path.join(process.cwd(), instrFile), mdContent);
    return instrFile;
}

const server = http.createServer((req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS' || req.method === 'HEAD') {
        res.writeHead(200);
        return res.end();
    }

    if (req.url === '/api/settings' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(globalSettings));
        return;
    }

    if (req.url === '/api/settings' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            try {
                const newSet = JSON.parse(body);
                globalSettings = { ...globalSettings, ...newSet };
                fs.writeFileSync(SETTINGS_FILE, JSON.stringify(globalSettings, null, 2));
                logEmitter.emit('log', { type: 'system', message: `Global settings updated.` });
                res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
            } catch(e) {
                res.writeHead(400); res.end(JSON.stringify({ error: 'Invalid JSON' }));
            }
        });
        return;
    }

    if (req.url === '/api/config' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => { body += chunk; });
        req.on('end', () => {
            const config = JSON.parse(body);
            const originalSessionName = config.session_name || 'agent-tunnel';
            const validSessionName = originalSessionName.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '');
            const configFile = path.join(CONFIGS_DIR, `${originalSessionName}.json`);
            
            logEmitter.emit('log', { type: 'system', message: `🚀 Starting Agent Tunnel: ${originalSessionName}` });
            fs.writeFileSync(configFile, JSON.stringify(config, null, 2));

            // Immediate injection of instruction file so the agent knows what's happening
            const injectedFile = generateActivationFiles(validSessionName, config, originalSessionName, false);
            logEmitter.emit('log', { type: 'system', message: `📝 Injected ${injectedFile} into project folder.` });

            const pubKey = ensureSshKey();
            const conn = new Client();
            
            logEmitter.emit('log', { type: 'system', message: `🔍 Verifying SSH at ${config.host}...` });

            conn.on('ready', () => {
                logEmitter.emit('log', { type: 'system', message: '✅ SSH Connected. Authorizing key...' });
                const setupCmd = `mkdir -p ~/.ssh && echo "${pubKey.trim()}" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh`;
                
                conn.exec(setupCmd, (err2, stream2) => {
                    const finalizeSsh = () => {
                        conn.end();
                        const sshKeyPath = path.join(os.homedir(), '.ssh', 'id_rsa_bridge');
                        const testCmd = `ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i "${sshKeyPath}" ${config.user}@${config.host} "echo 'success'"`;
                        
                        exec(testCmd, (testErr, testStdout) => {
                            if (testErr || !testStdout.includes('success')) {
                                logEmitter.emit('log', { type: 'error', message: '❌ SSH Key rejected. Direct Mode only.' });
                                generateActivationFiles(validSessionName, config, originalSessionName, false);
                                if (!res.writableEnded) {
                                    res.writeHead(200); res.end(JSON.stringify({ status: 'warning', message: 'Connected without sync (Key rejected).' }));
                                }
                                return;
                            }

                            logEmitter.emit('log', { type: 'system', message: '✅ Key validated. Starting Mutagen...' });
                            exec(`mutagen sync terminate "${validSessionName}"`, () => {
                                const mutagenEnv = { ...process.env, MUTAGEN_SSH_PATH: `ssh -i "${sshKeyPath}" -o BatchMode=yes -o StrictHostKeyChecking=no` };
                                const mutagenProc = spawn('mutagen', [
                                    'sync', 'create', `--name=${validSessionName}`,
                                    config.local_path, `${config.user}@${config.host}:${config.remote_path}`,
                                    '--sync-mode=two-way-resolved'
                                ], { env: mutagenEnv });

                                let errorBuf = '';
                                mutagenProc.stderr.on('data', (d) => {
                                    errorBuf += d.toString();
                                    logEmitter.emit('log', { type: 'error', message: `Mutagen: ${d.toString().trim()}` });
                                });

                                mutagenProc.on('close', (code) => {
                                    const success = (code === 0);
                                    generateActivationFiles(validSessionName, config, originalSessionName, success);
                                    logEmitter.emit('log', { type: 'system', message: success ? '✨ Tunnel & Sync active!' : '⚠️ Tunnel active (No sync).' });
                                    if (!res.writableEnded) {
                                        res.writeHead(200); res.end(JSON.stringify({ status: success ? 'success' : 'warning', message: 'Agent Tunnel connected.' }));
                                    }
                                });
                            });
                        });
                    };
                    if (stream2) stream2.on('close', finalizeSsh).resume();
                    else finalizeSsh();
                });
            }).on('error', (err) => {
                logEmitter.emit('log', { type: 'error', message: `❌ Error: ${err.message}` });
                if (!res.writableEnded) {
                    res.writeHead(500); res.end(JSON.stringify({ status: 'error', message: err.message }));
                }
            }).connect({ host: config.host, username: config.user, password: config.password, readyTimeout: 15000 });
        });
        return;
    }

    if (req.url === '/api/log' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => { logEmitter.emit('log', JSON.parse(body)); res.writeHead(200); res.end('OK'); });
        return;
    }

    if (req.url === '/api/log-stream') {
        res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive' });
        const listener = (msg) => res.write(`data: ${JSON.stringify(msg)}\n\n`);
        logEmitter.on('log', listener);
        req.on('close', () => logEmitter.removeListener('log', listener));
        return;
    }

    if (req.url === '/api/get-configs' && req.method === 'GET') {
        const files = fs.readdirSync(CONFIGS_DIR).filter(f => f.endsWith('.json'));
        const configs = {};
        for (const file of files) {
            try { configs[file.replace('.json', '')] = JSON.parse(fs.readFileSync(path.join(CONFIGS_DIR, file), 'utf8')); } catch(e) {}
        }
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(configs));
        return;
    }

    if (req.url === '/api/test-ssh' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const config = JSON.parse(body);
            const conn = new Client();
            conn.on('ready', () => { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ status: 'success' })); conn.end(); })
                .on('error', (err) => { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ status: 'error', message: err.message })); })
                .connect({ host: config.host, username: config.user, password: config.password, timeout: 5000 });
        });
        return;
    }

    if (req.url === '/api/delete-session' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const { name } = JSON.parse(body);
            const configFile = path.join(CONFIGS_DIR, `${name}.json`);
            if (fs.existsSync(configFile)) {
                fs.unlinkSync(configFile);
                logEmitter.emit('log', { type: 'system', message: `Session deleted: ${name}` });
                res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
            } else {
                res.writeHead(404); res.end(JSON.stringify({ status: 'error', message: 'Not found' }));
            }
        });
        return;
    }

    if (req.url === '/api/ls-local' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const { path: p } = JSON.parse(body);
            const target = p || process.cwd();
            try {
                const dirs = fs.readdirSync(target, { withFileTypes: true }).filter(f => f.isDirectory() && !f.name.startsWith('.')).map(f => f.name).sort();
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ dirs, current: target }));
            } catch (e) { res.writeHead(500); res.end(JSON.stringify({ error: e.message })); }
        });
        return;
    }

    if (req.url === '/api/ls-remote' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const config = JSON.parse(body);
            const conn = new Client();
            const target = config.remote_path || '/';
            conn.on('ready', () => {
                conn.sftp((err, sftp) => {
                    if (err || !sftp) return useLsFallback(conn, target, res);
                    sftp.readdir(target, (err, list) => {
                        if (err) return useLsFallback(conn, target, res);
                        const dirs = list.filter(f => f.attrs.isDirectory() && !f.filename.startsWith('.')).map(f => f.filename).sort();
                        res.writeHead(200, { 'Content-Type': 'application/json' });
                        res.end(JSON.stringify({ dirs, current: target }));
                        conn.end();
                    });
                });
            }).on('error', (err) => { res.writeHead(200); res.end(JSON.stringify({ error: err.message })); }).connect({ host: config.host, username: config.user, password: config.password, timeout: 5000 });
        });
        return;
    }

    if (req.url === '/api/sessions') {
        exec('mutagen sync list', (err, stdout) => {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ output: stdout || '' }));
        });
        return;
    }

    const projectPublic = path.join(__dirname, 'public', req.url === '/' ? 'index.html' : req.url);
    if (fs.existsSync(projectPublic) && fs.lstatSync(projectPublic).isFile()) {
        const ext = path.extname(projectPublic);
        const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }[ext] || 'text/plain';
        res.writeHead(200, { 'Content-Type': mime });
        fs.createReadStream(projectPublic).pipe(res);
    } else {
        res.writeHead(404); res.end();
    }
});

function useLsFallback(conn, target, res) {
    const cmd = `ls -p "${target}" | grep / | sed 's/\\///'`;
    conn.exec(cmd, (err, stream) => {
        if (err) { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ error: err.message })); return conn.end(); }
        let out = '';
        stream.on('data', (d) => out += d);
        stream.on('close', () => {
            const dirs = out.split('\n').map(d => d.trim()).filter(d => d && !d.startsWith('.')).sort();
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ dirs, current: target }));
            conn.end();
        }).resume();
    });
}

server.listen(PORT, () => {
    console.log(`[Agent Tunnel] running at http://localhost:${PORT}`);
});
